### ISSUE TITLE
Implement `Clique` consensus

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#11]
# Overview
Scroll uses [Clique](https://github.com/ethereum/EIPs/issues/225) consensus and as such we should provide an implementation of Clique consensus. This will allow for block headers to be gossiped over the p2p network and validated. For milestone 1 this is not a hard requirement, we can instead use the [`noop` consensus implementation](https://github.com/paradigmxyz/reth/blob/main/crates/consensus/consensus/src/noop.rs).

**Comment by greged93** [comment]
Note for when we implement the `Consensus`: as far as I could see given the interface of the trait, the `Consensus` seems to be to place where would we perform [block validation](https://github.com/paradigmxyz/reth/blob/a7bb1d1fa33836533d8e3f1c07d64f4872cb1d5f/crates/consensus/consensus/src/lib.rs#L116-L126), which should include the validation for the L1 messages ordering.

**Comment by frisitano** [comment]
It has been decided that Clique will be deprecated and as such we should not implement Clique in reth.
