### ISSUE TITLE
Implement `ChainSpec` and `HardForks`

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#12]
# Overview
We must implement a `ChainSpec` and `HardForks` for scroll and also scroll sepolia testnet.

# `Hardfork`
The `Hardfork` is used to determine the block number and timestamp at which features / functionality is changed. An example of a `Hardfork` implementation for `Optimism` can be found [here](https://github.com/scroll-tech/reth/tree/scroll/crates/optimism/hardforks). It should be noted that there is an expectation for hardforks to be mixed with ethereum hardforks as stated here:
https://github.com/scroll-tech/reth/blob/9c9d82c6bd1199ba0392a76a570001f9c9fa021e/crates/optimism/hardforks/src/hardfork.rs#L17-L36

We should review the hardforks introduce in [scrolls fork of revm](https://github.com/scroll-tech/revm/blob/scroll-evm-executor/v49/crates/primitives/src/specification.rs) which are feature gated in the link provided. We should then implement a pattern similar to optimism by creating a crate to define these in reth for scroll. These will then be subsequently integrated with the revm hardfork type as seen below in the optimism example (this is outside of the scope of this issue and should be handled in https://github.com/scroll-tech/reth/issues/5):
https://github.com/scroll-tech/reth/blob/9c9d82c6bd1199ba0392a76a570001f9c9fa021e/crates/optimism/evm/src/config.rs#L5-L30

# `ChainSpec`
The `ChainSpec` defines the core primitives of the chain such as the chain id, state genesis data, hardforks and other properties relating to the chain. A comprehensive view of the `ChainSpec` can be seen by observing the data structure:
https://github.com/scroll-tech/reth/blob/9c9d82c6bd1199ba0392a76a570001f9c9fa021e/crates/chainspec/src/spec.rs#L171-L216

We should follow a similar pattern as `Optimism` and implement a crate for scrolls `ChainSpec` associated types. The `Optimism` example can be found [here](https://github.com/scroll-tech/reth/tree/scroll/crates/optimism/chainspec). We should implement a spec for both scroll mainnet and scroll sepolia.

**Comment by greged93** [comment]
Should we add the `fee_vault_address` as part of the `ScrollChainSpec`? 

This would follow the pattern used in [l2geth](https://github.com/scroll-tech/go-ethereum/blob/9fff27e4f34fb5097100ed76ee725ce056267f4b/params/config.go#L646) and allow us to introduce [ScrollEvmConfig](https://github.com/paradigmxyz/reth/blob/5a522412af0e32606d5e5ec8d1c50b792a32abad/crates/optimism/evm/src/lib.rs#L41-L45) and implement `ConfigureEvmEnv`, where we can set the coinbase for the block to the vault address.

**Comment by georgehao** [comment]
I think we need to add.

**Comment by greged93** [comment]
Closed by #56.
