### ISSUE TITLE
Implement Node Client

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#35]
### Describe the feature

We should implement a node client that is configured appropriate for scroll reth.

**Comment by DaddyApex666** [comment]
Can you buy chance direct me to the best place to learn crypto from their creation to market please? I have dabbled with crypto for close to 10 years and I have little understanding as to how I can passively acquire crypto. Please help and Thank you. 
Cardboard

**Comment by frisitano** [comment]
completed by #68
