### ISSUE TITLE
Integrate Noop Consensus in Scroll Client

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#38]
### Describe the feature

# Overview
In the first instance for milestone 1 we will leverage a Noop consensus implementation such that we do not verify any fields in the block header during block import. In the future we will consider implementing clique consensus (#11).

**Comment by greged93** [comment]
@frisitano I think we can close this as Reth provides a [NoopConsensus](https://github.com/paradigmxyz/reth/blob/242bbaa9c460d90b5a307926d9810a22d1585cfc/crates/consensus/consensus/src/noop.rs#L8)

**Comment by frisitano** [comment]
Yes, this issue was just to specify that we should use Noop when we define the node implementation. I think we should keep it open until the Node is implemented.

**Comment by frisitano** [comment]
completed by #68
