### ISSUE TITLE
Milestone 1 Open Questions

### ISSUE THREAD

**Issue by greged93** [scroll-tech/reth#69]
### Describe the feature

List of open questions left for Milestone 1:

## Transaction type verification

We should check wether the verification of the transaction type should be placed in the execution strategy or rather moved at the consensus and transaction pool level.
Additional context: https://github.com/scroll-tech/reth/pull/63#discussion_r1874497682

**Comment by frisitano** [comment]
This is currently located in the `BlockExecutionStrategy` as seen below. I think this is a reasonable place for it to be.
https://github.com/scroll-tech/reth/blob/92c3a336a3c6ef72e6266b8d8f288dcb9b076f49/crates/scroll/evm/src/execute.rs#L129-L156

@greged93 would you agree? If so we can go ahead and close this issue.

**Comment by greged93** [comment]
Yes I think we can keep it there for now
