### ISSUE TITLE
Turn off required re-approval for new commits

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#70]
### Describe the feature

Currently, when we have approval on a PR and we submit a new commit the approval is marked as stale. I propose that we turn off this option such that approval is not dismissed. It is often the case that we will approve pending some small change that we do not need to re-review. 

This can be done in branch protection rules, I believe there should be an option "Dismiss stale pull request approvals when new commits are pushed".

**Comment by Thegaram** [comment]
Isn't this the case that:
1. My approval of a PR might change as new changes are pushed (e.g. the change might introduce a bug), and
2. If there's only small changes pushed it's easy to do a fast differential review by just reviewing the new commits.

These are the reason that I prefer to require re-approval for new commits. But if you feel strongly against it, and you think it slows down development, then we can turn it off for now.

**Comment by Thegaram** [comment]
Alternatively we can allow @frisitano to bypass checks when merging a PR. So it would be your call that previous approvals are sufficient and not invalidated by subsequent changes.

**Comment by frisitano** [comment]
> Alternatively we can allow @frisitano to bypass checks when merging a PR. So it would be your call that previous approvals are sufficient and not invalidated by subsequent changes.

I would be in favor of this suggestion.

**Comment by Thegaram** [comment]
Updated the ruleset.
