### ISSUE TITLE
Abstract provider via `NodeTypes`

### ISSUE THREAD

**Issue by greged93** [scroll-tech/reth#76]
### Describe the feature

Currently, we use a `scroll` feature gate and a concrete `Provider` type in multiple spots (example [1](https://github.com/scroll-tech/reth/blob/1d8f4e9a80bfeb6229c3a63d2e13ddb0fbd2a3a8/crates/engine/tree/src/tree/mod.rs#L2206) and [2](https://github.com/scroll-tech/reth/blob/2b41f7f91a969d33dffb2513e865e3c45eb0f5c1/crates/exex/exex/src/backfill/job.rs#L217)) in the code in order to pass our cache provider implementation `ScrollStateProviderDatabase` to the executor. This should be abstracted by pulling the provider to upstream via the `NodeTypes` trait.

**Comment by frisitano** [comment]
We will be deprecating support for Scroll's BMPT and as such this abstraction will no longer be required.
