### ISSUE TITLE
Long `write_preparation_duration` in `ExecutionStage`

### ISSUE THREAD

**Issue by greged93** [scroll-tech/reth#84]
### Describe the bug

A very long write `write_preparation_duration` was observed for syncing up to block 200k. Below is the log for the sync:
`Execution time block_fetch=4.891977062s execution=594.966989208s write_preparation=2301.219198s write=11.154126291s`.

Write preparation is mostly associated with the [finalization](https://github.com/scroll-tech/reth/blob/scroll/crates/stages/stages/src/stages/execution.rs#L400) of the `State<DB>`, which for Scroll includes [computing](https://github.com/scroll-tech/reth/blob/scroll/crates/scroll/revm/src/states/account_info.rs#L34) the Poseidon code hash.

### Steps to reproduce

`RUST_LOG=debug c run --bin scroll-reth --features scroll --manifest-path crates/scroll/bin/Cargo.toml -- node --chain scroll-mainnet --debug.tip 0x64fb69aa5ff5045e65da7da34f2fd9b82a304b4809b7ecaedeca1bc530aa4adc`

### Platform(s)

Mac (Intel)

### What version/commit are you on?

reth-scroll-cli Version: 1.1.2
Commit SHA: 5f376659e6aea31101e958317778dcecc913edf3
Build Timestamp: 2024-12-16T08:30:15.422248000Z
Build Features: scroll
Build Profile: debug

### What database version are you on?

Current database version: 2
Local database version: 2

### Which chain / network are you on?

scroll-mainnet

### What type of node are you running?

Archive (default)

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by frisitano** [comment]
How big of an undertaking would it be to introduce a `scroll-revm-fork` flag in https://github.com/scroll-tech/reth/blob/133d9c0a3f3ead0074ffb6919aaacc55d472050a/crates/scroll/revm/src/states/account_info.rs#L27-L46
when the flag is activated we take the values directly from the `AccountInfo`? If it is just a few line changes then it may be justified to implement it such that we can get better insights into sync speed.

**Comment by greged93** [comment]
Should be limited yes, will verify that I can reproduce the issue again and if the removal of the code hashing improves the speed. If so will open a PR for the fix.

**Comment by greged93** [comment]
update: I was able to reproduce the issue, getting a similar time on the `write_preparation` section (`Execution time block_fetch=4.915319708s execution=594.945075527s write_preparation=2310.43604325s write=10.975695292s
`).

Removing the code hashing step yielded `Execution time block_fetch=6.010938316s execution=593.838256963s write_preparation=447.842083ms write=11.031998958s`. Given the huge difference, I think the small work required to introduce the feature flag is worth it.

**Comment by greged93** [comment]
@frisitano, wondering if having the feature is really useful: as soon as we transition out of the revm fork into the sdk pattern, code behind the `scroll-revm-fork` feature won't pass the `clippy --all-features` check anymore and will have to be removed. Maybe we can just comment out the context part for now?

**Comment by frisitano** [comment]
> @frisitano, wondering if having the feature is really useful: as soon as we transition out of the revm fork into the sdk pattern, code behind the `scroll-revm-fork` feature won't pass the `clippy --all-features` check anymore and will have to be removed. Maybe we can just comment out the context part for now?

Yep if it's easier then let's just comment it out for now. Add some TODO inline and open an issue so we have this tracked.
